name: Trigger Quartz build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build and Deploy in GH Page
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_B_TOKEN }}" \
            https://api.github.com/repos/IRIS-Digital-Dosimeter/IRIS-Digital-Dosimeter.github.io/dispatches \
            -d '{"event_type":"trigger-from-vault"}'
